const PASSWORD_SALT = 10;
const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
const USER_DOESNT_EXIST = "USER_DOESNT_EXIST";
const INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
const USER_ROLES = {
  ADMIN: "ADMIN",
  CLIENT: "CLIENT"
}

module.exports = {
  PASSWORD_SALT,
  USER_ALREADY_EXISTS,
  USER_DOESNT_EXIST,
  INCORRECT_PASSWORD,
  USER_ROLES
};
